### PR TITLE
feat: OverlayFS -> AUFS whiteout conversion

### PR DESCRIPTION
**Pull request by dtrudg**
Allow OverlayFS whiteouts to be converted to AUFS, by filtering a tar stream.

In this direction the conversion is a single pass, single operation. There is no requirement to pre-scan the tar.

Close https://github.com/sylabs/oci-tools/issues/53

### CODE REVIEW

**Review by tri-adam — APPROVED** [review]
LGTM. Just one observation, the round trip exposes that _some_ of the TAR entries end up getting `Clean`ed, while others do not. I'm not aware of any specific issue this causes, but thought I'd raise it just in case you can think of any?

Specifically, the input in your test case is:

```
$ gunzip -c test/images/aufs-docker-v2-manifest/blobs/sha256/da55812559dec81445c289c3832cee4a2f725b15aeb258791640185c3126b2bf | tar tf - 
./
./dir/
./dir/.wh..wh..opq
./.wh.file
```

When converted to OverlayFS, you end up with the whited out `file` trimmed of its `./`:

```
$ tar tf 'pkg/mutate/testdata/Test_WhiteoutRoundTrip/overlayfs.golden'
./
./dir/
file
```

And then of course when you go back the other direction, both whiteout files have also been trimmed of their leading `./`.

```
$ tar tf 'pkg/mutate/testdata/Test_WhiteoutRoundTrip/aufs.golden'
./
./dir/
dir/.wh..wh..opq
.wh.file
```

**Comment by dtrudg** [comment]
> LGTM. Just one observation, the round trip exposes that _some_ of the TAR entries end up getting `Clean`ed, while others do not. I'm not aware of any specific issue this causes, but thought I'd raise it just in case you can think of any?

Right - they are equivalent, but yeah.. it would be nicer for comparison purposes if the `./` is preserver. Let me look at that.

**Comment by dtrudg** [comment]
@tri-adam - please take a look at 6498921

```
09:36 am $ gunzip -c test/images/aufs-docker-v2-manifest/blobs/sha256/da55812559dec81445c289c3832cee4a2f725b15aeb258791640185c3126b2bf | tar tf -
./
./dir/
./dir/.wh..wh..opq
./.wh.file

09:36 am $ tar tf pkg/mutate/testdata/Test_WhiteoutRoundTrip/overlayfs.golden 
./
./dir/
./file

09:36 am $ tar tf pkg/mutate/testdata/Test_WhiteoutRoundTrip/aufs.golden 
./
./dir/
./dir/.wh..wh..opq
./.wh.file
```

**Review by tri-adam — APPROVED** [review]
LGTM

**Pull request merged**
